#include "parser/json/json.h"
#include <stdio.h>

void print_json(int level, struct json_value *tree)
{
    int i, j;
    for(i = 0; i < tree->value_count; i++)
    {
        struct json_value *value = tree->values[i];

        switch(value->type)
        {
            case JSON_TYPE_NOVALUE:
            {
                for(j = 0; j < level; j++)
                    printf("  ");

                printf("- %s\n", value->key);
                break;
            }
            case JSON_TYPE_STRING:
            {
                for(j = 0; j < level; j++)
                    printf("  ");

                printf("- %s : %s\n", value->key, value->string_value);
                break;
            }
            case JSON_TYPE_OBJECT:
            case JSON_TYPE_ARRAY:
            {
                for(j = 0; j < level; j++)
                    printf("  ");

                printf("- %s : %d []\n", value->key, value->value_count);

                print_json(level + 1, value);

                break;
            }
        }
    }
}

int main(void)
{
    char *json =
	"[\n"
"    {\n"
"        \"name\": \"Alabama\",\n"
"        \"abbreviation\": \"AL\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Alaska\",\n"
"        \"abbreviation\": \"AK\"\n"
"    },\n"
"    {\n"
"        \"name\": \"American Samoa\",\n"
"        \"abbreviation\": \"AS\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Arizona\",\n"
"        \"abbreviation\": \"AZ\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Arkansas\",\n"
"        \"abbreviation\": \"AR\"\n"
"    },\n"
"    {\n"
"        \"name\": \"California\",\n"
"        \"abbreviation\": \"CA\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Colorado\",\n"
"        \"abbreviation\": \"CO\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Connecticut\",\n"
"        \"abbreviation\": \"CT\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Delaware\",\n"
"        \"abbreviation\": \"DE\"\n"
"    },\n"
"    {\n"
"        \"name\": \"District Of Columbia\",\n"
"        \"abbreviation\": \"DC\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Federated States Of Micronesia\",\n"
"        \"abbreviation\": \"FM\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Florida\",\n"
"        \"abbreviation\": \"FL\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Georgia\",\n"
"        \"abbreviation\": \"GA\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Guam\",\n"
"        \"abbreviation\": \"GU\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Hawaii\",\n"
"        \"abbreviation\": \"HI\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Idaho\",\n"
"        \"abbreviation\": \"ID\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Illinois\",\n"
"        \"abbreviation\": \"IL\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Indiana\",\n"
"        \"abbreviation\": \"IN\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Iowa\",\n"
"        \"abbreviation\": \"IA\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Kansas\",\n"
"        \"abbreviation\": \"KS\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Kentucky\",\n"
"        \"abbreviation\": \"KY\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Louisiana\",\n"
"        \"abbreviation\": \"LA\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Maine\",\n"
"        \"abbreviation\": \"ME\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Marshall Islands\",\n"
"        \"abbreviation\": \"MH\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Maryland\",\n"
"        \"abbreviation\": \"MD\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Massachusetts\",\n"
"        \"abbreviation\": \"MA\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Michigan\",\n"
"        \"abbreviation\": \"MI\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Minnesota\",\n"
"        \"abbreviation\": \"MN\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Mississippi\",\n"
"        \"abbreviation\": \"MS\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Missouri\",\n"
"        \"abbreviation\": \"MO\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Montana\",\n"
"        \"abbreviation\": \"MT\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Nebraska\",\n"
"        \"abbreviation\": \"NE\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Nevada\",\n"
"        \"abbreviation\": \"NV\"\n"
"    },\n"
"    {\n"
"        \"name\": \"New Hampshire\",\n"
"        \"abbreviation\": \"NH\"\n"
"    },\n"
"    {\n"
"        \"name\": \"New Jersey\",\n"
"        \"abbreviation\": \"NJ\"\n"
"    },\n"
"    {\n"
"        \"name\": \"New Mexico\",\n"
"        \"abbreviation\": \"NM\"\n"
"    },\n"
"    {\n"
"        \"name\": \"New York\",\n"
"        \"abbreviation\": \"NY\"\n"
"    },\n"
"    {\n"
"        \"name\": \"North Carolina\",\n"
"        \"abbreviation\": \"NC\"\n"
"    },\n"
"    {\n"
"        \"name\": \"North Dakota\",\n"
"        \"abbreviation\": \"ND\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Northern Mariana Islands\",\n"
"        \"abbreviation\": \"MP\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Ohio\",\n"
"        \"abbreviation\": \"OH\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Oklahoma\",\n"
"        \"abbreviation\": \"OK\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Oregon\",\n"
"        \"abbreviation\": \"OR\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Palau\",\n"
"        \"abbreviation\": \"PW\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Pennsylvania\",\n"
"        \"abbreviation\": \"PA\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Puerto Rico\",\n"
"        \"abbreviation\": \"PR\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Rhode Island\",\n"
"        \"abbreviation\": \"RI\"\n"
"    },\n"
"    {\n"
"        \"name\": \"South Carolina\",\n"
"        \"abbreviation\": \"SC\"\n"
"    },\n"
"    {\n"
"        \"name\": \"South Dakota\",\n"
"        \"abbreviation\": \"SD\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Tennessee\",\n"
"        \"abbreviation\": \"TN\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Texas\",\n"
"        \"abbreviation\": \"TX\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Utah\",\n"
"        \"abbreviation\": \"UT\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Vermont\",\n"
"        \"abbreviation\": \"VT\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Virgin Islands\",\n"
"        \"abbreviation\": \"VI\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Virginia\",\n"
"        \"abbreviation\": \"VA\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Washington\",\n"
"        \"abbreviation\": \"WA\"\n"
"    },\n"
"    {\n"
"        \"name\": \"West Virginia\",\n"
"        \"abbreviation\": \"WV\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Wisconsin\",\n"
"        \"abbreviation\": \"WI\"\n"
"    },\n"
"    {\n"
"        \"name\": \"Wyoming\",\n"
"        \"abbreviation\": \"WY\"\n"
"    }\n"
"]";

    struct json_value *tree = json_parse(json);

    print_json(0, tree);

    json_delete(tree);

    return 0;
}
